In [3]:
import torch
a =  torch.tensor(2.0)
b = torch.tensor(3.0)

In [7]:
a * b, a + b, a - b, a / b, a ** b

(tensor(6.), tensor(5.), tensor(-1.), tensor(0.6667), tensor(8.))

In [9]:
x = torch.tensor([1,2,3,4])

In [10]:
x[3]

tensor(4)

In [11]:
len(x)

4

In [12]:
A = torch.arange(20).reshape((5,4))

In [13]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [15]:
A * 3

tensor([[ 0,  3,  6,  9],
        [12, 15, 18, 21],
        [24, 27, 30, 33],
        [36, 39, 42, 45],
        [48, 51, 54, 57]])

In [16]:
A * torch.tensor(3)

tensor([[ 0,  3,  6,  9],
        [12, 15, 18, 21],
        [24, 27, 30, 33],
        [36, 39, 42, 45],
        [48, 51, 54, 57]])

In [22]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

In [23]:
a * b

tensor([ 4, 10, 18])

In [24]:
A * a

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [27]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [28]:
c = torch.tensor([1,2,3,4])
A * c

tensor([[ 0,  2,  6, 12],
        [ 4, 10, 18, 28],
        [ 8, 18, 30, 44],
        [12, 26, 42, 60],
        [16, 34, 54, 76]])

In [32]:
B = torch.arange(20).reshape((5,4)) + 3

In [34]:
B

tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])

In [35]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [36]:
A * B

tensor([[  0,   4,  10,  18],
        [ 28,  40,  54,  70],
        [ 88, 108, 130, 154],
        [180, 208, 238, 270],
        [304, 340, 378, 418]])

In [39]:
C = B[:3, :]

In [41]:
C

tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]])

In [42]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [47]:
C = B[:, :3]

In [48]:
C

tensor([[ 3,  4,  5],
        [ 7,  8,  9],
        [11, 12, 13],
        [15, 16, 17],
        [19, 20, 21]])

In [49]:
A * C

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [50]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [51]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [52]:
A == A.T

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [53]:
X = torch.arange(24).reshape(2,3,4)

In [54]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [55]:
X.sum()

tensor(276)

In [57]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [59]:
X.shape

torch.Size([2, 3, 4])

In [60]:
X.sum(axis=0)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [61]:
X.sum(axis=1)

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [62]:
Y = torch.arange(12).reshape(4,3)

In [63]:
Y

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [77]:
Y.sum()

tensor(66)

In [65]:
Y.sum(axis=0)

tensor([18, 22, 26])

In [66]:
Y.sum(axis=1)

tensor([ 3, 12, 21, 30])

In [92]:
Y = torch.arange(12, dtype=torch.float).reshape((4,3))

In [93]:
Y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [94]:
Y.shape

torch.Size([4, 3])

In [95]:
Y.sum()

tensor(66.)

In [96]:
Y.mean()

tensor(5.5000)

In [98]:
Y.sum(axis=1)

tensor([ 3., 12., 21., 30.])

In [99]:
Y.sum(axis=[0,1])

tensor(66.)

In [102]:
Y.mean(axis=0)

tensor([4.5000, 5.5000, 6.5000])

In [106]:
Y.sum(axis=1, keepdims=True)

tensor([[ 3.],
        [12.],
        [21.],
        [30.]])

In [14]:
Y

NameError: name 'Y' is not defined

In [10]:
import torch
x = torch.arange(3, dtype=torch.float)
y = torch.arange(3, dtype=torch.float)

In [13]:
torch.dot(x, y)

tensor(5.)

In [25]:
a = torch.arange(20).reshape((4, 5))
b = torch.arange(12).reshape((3, 4))
print(b)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


In [28]:
print(b.size(1))
print(a.size(0))

4
4


In [31]:
torch.mm(b, a)

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462]])