In [1]:
import torch

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.randn(3, 4)

tensor([[ 0.1731,  0.1419, -0.2195, -0.8159],
        [-0.6949, -0.3574,  0.9286,  1.1144],
        [-1.3904, -0.5968, -0.1552,  1.5057]])

In [10]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([5,6,7,8])

x + y

tensor([ 6,  8, 10, 12])

In [11]:
x * y

tensor([ 5, 12, 21, 32])

In [12]:
x ** y

tensor([    1,    64,  2187, 65536])

In [13]:
x - y

tensor([-4, -4, -4, -4])

In [17]:
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5982])

In [29]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [48]:
a = torch.arange(3).reshape(3,1)

In [46]:
b = torch.arange(2).reshape(1,2)

In [50]:
a

tensor([[0],
        [1],
        [2]])

In [51]:
b

tensor([[0, 1]])

In [52]:
a  + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [53]:
b

tensor([[0, 1]])

In [55]:
x = a+ b

In [56]:
x[-1]

tensor([2, 3])

In [57]:
x[1:3]

tensor([[1, 2],
        [2, 3]])

In [58]:
x

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [59]:
x[1,1] = 3

In [60]:
x

tensor([[0, 1],
        [1, 3],
        [2, 3]])

In [61]:
x

tensor([[0, 1],
        [1, 3],
        [2, 3]])

In [62]:
x[0:2, 99]

IndexError: index 99 is out of bounds for dimension 1 with size 2

In [63]:
x[0:2, 1] = 99

In [64]:
x

tensor([[ 0, 99],
        [ 1, 99],
        [ 2,  3]])

In [65]:
id(x)

140590453553648

In [102]:
X = torch.randn((3,4))
Y = torch.randn((3,4))
Z = torch.ones_like(X)
old = id(Z)
Z[:] = X + Y
print(old)
print(id(Z))

140590453954096
140590453954096


In [87]:
M = X + Y

In [88]:
M

tensor([[ 2.4840, -1.3649, -2.5839,  2.0014],
        [-1.0720,  0.9227,  0.2526, -0.0187],
        [ 1.1150, -1.8523, -0.7591,  0.9233]])

In [93]:
M[:,1::2]

tensor([[-1.3649,  2.0014],
        [ 0.9227, -0.0187],
        [-1.8523,  0.9233]])

In [94]:
M.shape

torch.Size([3, 4])

In [95]:
M.numel()

12

In [96]:
X

tensor([[ 1.0520, -1.0039, -0.6396,  0.1303],
        [-0.0286,  1.0080,  0.0110,  0.0602],
        [ 0.4425,  0.3002,  0.7484,  0.5112]])

In [97]:
Y

tensor([[ 1.4321, -0.3610, -1.9443,  1.8711],
        [-1.0434, -0.0853,  0.2417, -0.0789],
        [ 0.6725, -2.1524, -1.5076,  0.4121]])

In [106]:
a = torch.tensor([1])

In [113]:
a, a.item(), int(a)

(tensor([1]), 1, 1, True)

In [117]:
import os
os.makedirs(os.path.join('data'), exist_ok=True)
datafile = os.path.join('data', 'house_tiny.csv')
with open(datafile, 'w') as f:
    f.write('NumRooms, Alley, Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [120]:
import pandas as pd
data = pd.read_csv(datafile)
print(data)

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000


In [128]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, -1]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  Alley
0       3.0   Pave
1       2.0    NaN
2       4.0    NaN
3       3.0    NaN


In [129]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms   Alley_Pave   Alley_nan
0       3.0            1           0
1       2.0            0           1
2       4.0            0           1
3       3.0            0           1


In [132]:
X = torch.tensor(inputs.to_numpy(dtype=float))

In [134]:
Y = torch.tensor(outputs.to_numpy(dtype=float))

In [152]:
df = pd.read_csv(datafile)
print(df)

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000


In [154]:
df.isnull().sum()

NumRooms    2
 Alley      3
 Price      0
dtype: int64

In [155]:
idx = df.isnull().sum().idxmax()

In [159]:
print(df)

   NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000


In [161]:
df

NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000

In [167]:
torch.tensor(df.to_numpy(dtype=float))

tensor([[       nan, 1.2750e+05],
        [2.0000e+00, 1.0600e+05],
        [4.0000e+00, 1.7810e+05],
        [       nan, 1.4000e+05]], dtype=torch.float64)

In [168]:
df.shape

(4, 2)

In [2]:
import torch
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [4]:
torch.abs(u).sum()

tensor(7.)

In [5]:
torch.norm(torch.ones((4,9)))

tensor(6.)

In [13]:
torch.transpose(torch.ones((4,9)), dim0=0, dim1=0)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [20]:
a.sum(axis=1)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [18]:
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])